<?php

namespace Whilesmart\UserAuthentication\Tests\Feature;

use Whilesmart\UserAuthentication\Tests\TestCase;

class TwoFactorVerifyTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();
    }

    /** @test */
    public function test_it_fails_with_expired_session()
    {
        // No session set
        $response = $this->postJson('/api/2fa/verify', ['code' => '123456']);
        $response->assertStatus(401);
    }

    /** @test */
    public function test_it_verifies_email_2fa_code()
    {
        $user = $this->createUser();
        $user->twoFactorAuth()->create([
            'secret' => 'email-secret',
            'type' => 'email',
            'is_enabled' => true,
        ]);

        // Create the code entry in verification_codes table as generated by TwoFactorService
        \Whilesmart\UserAuthentication\Models\VerificationCode::create([
            'contact' => $user->email,
            'code' => \Illuminate\Support\Facades\Hash::make('654321'),
            'purpose' => 'login_email',
            'expires_at' => now()->addMinutes(5),
        ]);

        session([
            '2fa:user_id' => $user->id,
            '2fa:contact' => $user->email,
            '2fa:type' => 'email',
        ]);

        $response = $this->postJson('/api/2fa/verify', ['code' => '654321']);

        $response->assertStatus(200);
        $this->assertAuthenticatedAs($user);
        $this->assertTrue(session('2fa:verified'));
    }
}
