<?php

namespace Whilesmart\UserAuthentication\Tests\Feature;

use Whilesmart\UserAuthentication\Models\VerificationCode;
use Whilesmart\UserAuthentication\Services\TwoFactorService;
use Whilesmart\UserAuthentication\Tests\TestCase;

class TwoFactorVerifyTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();
    }

    /** @test */
    public function test_it_fails_with_invalid_pending_token()
    {
        $response = $this->postJson('/api/2fa/verify', [
            'two_factor_token' => 'invalid-token',
            'code' => '123456',
        ]);
        $response->assertStatus(401);
    }

    /** @test */
    public function test_it_verifies_email_2fa_code()
    {
        $user = $this->createUser();
        $user->twoFactorAuth()->create([
            'secret' => 'email-secret',
            'type' => 'email',
            'is_enabled' => true,
        ]);

        // Create the code entry in verification_codes table as generated by TwoFactorService
        VerificationCode::create([
            'contact' => $user->email,
            'code' => \Illuminate\Support\Facades\Hash::make('654321'),
            'purpose' => 'login_email',
            'expires_at' => now()->addMinutes(5),
        ]);

        $pendingToken = app(TwoFactorService::class)->generatePendingToken($user, $user->email, 'email');

        $response = $this->postJson('/api/2fa/verify', [
            'two_factor_token' => $pendingToken,
            'code' => '654321',
        ]);

        $response->assertStatus(200)
            ->assertJsonPath('data.token', fn (string $token) => ! empty($token));
    }

    /** @test */
    public function test_email_2fa_code_cannot_be_reused()
    {
        $user = $this->createUser();
        $user->twoFactorAuth()->create([
            'secret' => 'email-secret',
            'type' => 'email',
            'is_enabled' => true,
        ]);

        VerificationCode::create([
            'contact' => $user->email,
            'code' => \Illuminate\Support\Facades\Hash::make('654321'),
            'purpose' => 'login_email',
            'expires_at' => now()->addMinutes(5),
        ]);

        $service = app(TwoFactorService::class);
        $pendingToken = $service->generatePendingToken($user, $user->email, 'email');

        // First verification succeeds
        $this->postJson('/api/2fa/verify', [
            'two_factor_token' => $pendingToken,
            'code' => '654321',
        ])->assertStatus(200);

        // Replaying the same code with a fresh pending token must fail
        $freshPendingToken = $service->generatePendingToken($user, $user->email, 'email');
        $response = $this->postJson('/api/2fa/verify', [
            'two_factor_token' => $freshPendingToken,
            'code' => '654321',
        ]);
        $response->assertStatus(422)
            ->assertJson(['message' => 'Invalid or expired code.']);
    }
}
