<?php

namespace Whilesmart\UserAuthentication\Http\Controllers\Auth;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Whilesmart\UserAuthentication\Services\TwoFactorService;

class TwoFactorController extends Controller
{
    /**
     * Verify the 2FA code (TOTP or Email/SMS)
     */
    public function verify(Request $request)
    {
        $userId = session('2fa:user_id');
        $contact = session('2fa:contact');
        $type = session('2fa:type');

        if (! $userId) {
            return response()->json(['message' => 'Session expired.'], 401);
        }

        $user = \Whilesmart\UserAuthentication\Models\User::find($userId);
        $smartPingsService = app(\Whilesmart\UserAuthentication\Services\SmartPingsVerificationService::class);

        // CASE 1: TOTP
        if ($user->twoFactorAuth->type === 'totp') {

            try {

                $valid = \PragmaRX\Google2FALaravel\Facade::verifyKey(
                    $user->twoFactorAuth->secret, // Eloquent 'encrypted' cast handles decryption
                    $request->code
                );
                // Check if valid
                if (! $valid) {
                    return response()->json(['message' => 'Invalid code.'], 422);
                }
            } catch (\Illuminate\Contracts\Encryption\DecryptException $e) {
                return response()->json([
                    'message' => 'The provided security token is invalid or the encryption key has changed.',
                ], 422);
            }
        }
        // CASE 2 & 3: Handled by the Service to keep Controller thin
        else {
            $service = app(TwoFactorService::class);
            if (! $service->verifyCode($contact, $request->code, $type)) {
                return $this->failure('Invalid or expired code.', 422);
            }
        }

        // AUTH SUCCESS
        Auth::login($user);  // Uncomment this to log in the user (required for test assertions)
        $token = $user->createToken('auth-token')->plainTextToken;
        session()->forget(['2fa:user_id', '2fa:contact', '2fa:type']);
        session(['2fa:verified' => true]);

        return response()->json(['message' => 'Authenticated successfully.', 'token' => $token]);

    }

    public function verifyLink(Request $request)
    {
        //get link that has not been used and matches the token in the request
        $link = \Whilesmart\UserAuthentication\Models\MagicLink::where('token', $request->token)->where('is_used', false)->first();
       
        // 1. Check if the URL signature is valid
        if (! $link || $link->isExpired() || ! $request->hasValidSignature()) {
            return $this->failure('The link has expired or is invalid.', 403);
        }

        // 2. Find the user based on the link
        $user = $link->user;
        // 3. Log them in and set the 2FA verified flag
        Auth::login($user);
        
        $link->update(['is_used' => true]);
        session(['2fa:verified' => true]);

        // 4. Redirect them or send a success JSON
        // Since this is likely an API package, you might redirect to your frontend dashboard
        $dashboardUrl = config('user-authentication.dashboard_url', '/dashboard');

        return redirect()->away($dashboardUrl);
    }

    /**
    * Resend the 2FA code (for email/SMS types)
    */
    public function resend(Request $request)
    {
        $userId = session('2fa:user_id');
        $contact = session('2fa:contact');
        $type = session('2fa:type');

        if (! $userId) {
            return response()->json(['message' => 'Session expired.'], 401);
        }

        $user = \Whilesmart\UserAuthentication\Models\User::find($userId);

        if ($type === 'totp') {
            return response()->json(['message' => 'TOTP codes are generated by your authenticator app. Please check there.'], 400);
        }

        app(TwoFactorService::class)->handleChallenge($user, $type, $contact);

        return response()->json(['message' => 'A new verification code has been sent.']);
    }
}
